CREATE TABLE IF NOT EXISTS public.chat_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel character varying(32) NOT NULL DEFAULT 'public',
    user_id integer NOT NULL REFERENCES public.users(id),
    username character varying(80) NOT NULL,
    namecolor character varying(16) NOT NULL DEFAULT 'ffffff',
    hat character varying(255),
    body text NOT NULL,
    body_html text NOT NULL,
    body_censored text NOT NULL,
    quotes integer,
    created_utc integer NOT NULL,
    has_attachment boolean NOT NULL DEFAULT false,
    removed_by_id integer REFERENCES public.users(id),
    removed_by_username character varying(80),
    distinguish_by_id integer REFERENCES public.users(id),
    distinguish_by_username character varying(80)
);

CREATE INDEX IF NOT EXISTS chat_messages_channel_id_idx
    ON public.chat_messages (channel, id DESC);
CREATE INDEX IF NOT EXISTS chat_messages_channel_created_idx
    ON public.chat_messages (channel, created_utc DESC);
CREATE INDEX IF NOT EXISTS chat_messages_author_idx
    ON public.chat_messages (lower(username), id DESC);